apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../base
- ingress.yaml
namespace: prod
commonAnnotations:
  supported-by: jbame@ac-itsolutions.net
labels:
- includeSelectors: false
  pairs:
    project: acit-website-deployment
patches:
- path: service.yaml
- path: preview-service.yaml
- path: rollout.yaml
